module.exports = {
    path:'/productList/all.json',
    template:{
      data: [{
        "key": "22",
        "name": "吉林",
        "orderSeq": "1",
        "newId": "220000",
        "newPid": "0",
        "newName": "吉林省",
        "opened": "FALSE"
      }, {
        "key": "44",
        "name": "广东",
        "orderSeq": "1",
        "newId": "440000",
        "newPid": "0",
        "newName": "广东省",
        "opened": "FALSE"
      }, {
        "key": "23",
        "name": "黑龙江",
        "orderSeq": "1",
        "newId": "230000",
        "newPid": "0",
        "newName": "黑龙江省",
        "opened": "FALSE"
      }, {
        "key": "45",
        "name": "广西",
        "orderSeq": "1",
        "newId": "450000",
        "newPid": "0",
        "newName": "广西壮族自治区",
        "opened": "FALSE"
      }, {
        "key": "46",
        "name": "海南",
        "orderSeq": "1",
        "newId": "460000",
        "newPid": "0",
        "newName": "海南省",
        "opened": "FALSE"
      }, {
        "key": "91",
        "name": "澳门",
        "orderSeq": "1",
        "newId": "820000",
        "newPid": "0",
        "newName": "澳门特别行政区",
        "opened": "FALSE"
      }, {
        "key": "71",
        "name": "台湾",
        "orderSeq": "1",
        "newId": "710000",
        "newPid": "0",
        "newName": "台湾省",
        "opened": "FALSE"
      }, {
        "key": "50",
        "name": "重庆",
        "orderSeq": "1",
        "newId": "500000",
        "newPid": "0",
        "newName": "重庆市",
        "opened": "FALSE"
      }, {
        "key": "72",
        "name": "台湾测试",
        "orderSeq": "1",
        "newId": "720000",
        "newPid": "0",
        "newName": "台湾测试",
        "opened": "FALSE"
      }, {
        "key": "51",
        "name": "四川",
        "orderSeq": "1",
        "newId": "510000",
        "newPid": "0",
        "newName": "四川省",
        "opened": "FALSE"
      }, {
        "key": "52",
        "name": "贵州",
        "orderSeq": "1",
        "newId": "520000",
        "newPid": "0",
        "newName": "贵州省",
        "opened": "FALSE"
      }, {
        "key": "31",
        "name": "上海",
        "orderSeq": "1",
        "newId": "310000",
        "newPid": "0",
        "newName": "上海市",
        "opened": "FALSE"
      }, {
        "key": "53",
        "name": "云南",
        "orderSeq": "1",
        "newId": "530000",
        "newPid": "0",
        "newName": "云南省",
        "opened": "FALSE"
      }, {
        "key": "10",
        "name": "全国",
        "orderSeq": "1",
        "newId": "10",
        "newPid": "0",
        "newName": "全国",
        "opened": "FALSE"
      }, {
        "key": "32",
        "name": "江苏",
        "orderSeq": "1",
        "newId": "320000",
        "newPid": "0",
        "newName": "江苏省",
        "opened": "FALSE"
      }, {
        "key": "54",
        "name": "西藏",
        "orderSeq": "1",
        "newId": "540000",
        "newPid": "0",
        "newName": "西藏自治区",
        "opened": "FALSE"
      }, {
        "key": "11",
        "name": "北京",
        "orderSeq": "1",
        "newId": "110000",
        "newPid": "0",
        "newName": "北京市",
        "opened": "FALSE"
      }, {
        "key": "33",
        "name": "浙江",
        "orderSeq": "1",
        "newId": "330000",
        "newPid": "0",
        "newName": "浙江省",
        "opened": "FALSE"
      }, {
        "key": "12",
        "name": "天津",
        "orderSeq": "1",
        "newId": "120000",
        "newPid": "0",
        "newName": "天津市",
        "opened": "FALSE"
      }, {
        "key": "34",
        "name": "安徽",
        "orderSeq": "1",
        "newId": "340000",
        "newPid": "0",
        "newName": "安徽省",
        "opened": "FALSE"
      }, {
        "key": "13",
        "name": "河北",
        "orderSeq": "1",
        "newId": "130000",
        "newPid": "0",
        "newName": "河北省",
        "opened": "FALSE"
      }, {
        "key": "35",
        "name": "福建",
        "orderSeq": "1",
        "newId": "350000",
        "newPid": "0",
        "newName": "福建省",
        "opened": "FALSE"
      }, {
        "key": "14",
        "name": "山西",
        "orderSeq": "1",
        "newId": "140000",
        "newPid": "0",
        "newName": "山西省",
        "opened": "FALSE"
      }, {
        "key": "36",
        "name": "江西",
        "orderSeq": "1",
        "newId": "360000",
        "newPid": "0",
        "newName": "江西省",
        "opened": "FALSE"
      }, {
        "key": "15",
        "name": "内蒙古",
        "orderSeq": "1",
        "newId": "150000",
        "newPid": "0",
        "newName": "内蒙古自治区",
        "opened": "FALSE"
      }, {
        "key": "37",
        "name": "山东",
        "orderSeq": "1",
        "newId": "370000",
        "newPid": "0",
        "newName": "山东省",
        "opened": "FALSE"
      }, {
        "key": "81",
        "name": "香港",
        "orderSeq": "1",
        "newId": "810000",
        "newPid": "0",
        "newName": "香港特别行政区",
        "opened": "FALSE"
      }, {
        "key": "61",
        "name": "陕西",
        "orderSeq": "1",
        "newId": "610000",
        "newPid": "0",
        "newName": "陕西省",
        "opened": "FALSE"
      }, {
        "key": "62",
        "name": "甘肃",
        "orderSeq": "1",
        "newId": "620000",
        "newPid": "0",
        "newName": "甘肃省",
        "opened": "FALSE"
      }, {
        "key": "41",
        "name": "河南",
        "orderSeq": "1",
        "newId": "410000",
        "newPid": "0",
        "newName": "河南省",
        "opened": "FALSE"
      }, {
        "key": "63",
        "name": "青海",
        "orderSeq": "1",
        "newId": "630000",
        "newPid": "0",
        "newName": "青海省",
        "opened": "FALSE"
      }, {
        "key": "42",
        "name": "湖北",
        "orderSeq": "1",
        "newId": "420000",
        "newPid": "0",
        "newName": "湖北省",
        "opened": "FALSE"
      }, {
        "key": "64",
        "name": "宁夏",
        "orderSeq": "1",
        "newId": "640000",
        "newPid": "0",
        "newName": "宁夏回族自治区",
        "opened": "FALSE"
      }, {
        "key": "21",
        "name": "辽宁",
        "orderSeq": "1",
        "newId": "210000",
        "newPid": "0",
        "newName": "辽宁省",
        "opened": "FALSE"
      }, {
        "key": "43",
        "name": "湖南",
        "orderSeq": "1",
        "newId": "430000",
        "newPid": "0",
        "newName": "湖南省",
        "opened": "FALSE"
      }, {
        "key": "65",
        "name": "新疆",
        "orderSeq": "1",
        "newId": "650000",
        "newPid": "0",
        "newName": "新疆维吾尔自治区",
        "opened": "FALSE"
      }],
      time: 1472436273622,
      code: '200',
      msg: '',
    },
  };
  